version: "3"
services:
  redis:
      image: redis

  db:
      image: postgres:9.4
      environment:
        POSTGRES_USER: postres
        POSTGRES_PASSWORD: postres

  voting-app:
      build: ./vote
      ports:
        - 5000:80

  result-app:
      build: ./result
      ports:
        - 5001:80
  worker-app:
      build: ./worker
